[build]
  publish = "client/build"
  command = "npm run heroku-postbuild"

[build.environment]
  CI = ""
  SECRETS_SCAN_ENABLED = "false"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200